#!/bin/bash

# Read environtment before run each script
run_script() {
    # Read the variables
    if [ -f $HOME/.ssh/common_env ]
    then
		while read -r line; do
		var=`echo $line | cut -d '=' -f1`; test=$(echo $var)
		if [ -z "$(test)" ];then eval export "$line";fi
		done <$HOME/.ssh/common_env
    fi
    # Call the script
    echo -e "$hrd\nRUN SCRIPT:\n$1\n$hr"
    sh $1; rm -f .io/$1;
}

# Listing script files to run
list_files() {
	[[ $1 == *"io/scripts"* ]] && TYPE=CUSTOM || TYPE=COMMON
	echo -e "\n$hrd\n$TYPE SCRIPTS\n$hrd"
	if ([ -d $1 ] && [ "$(ls -A $1)" ])
	then
		# Listing..
		chmod -R +x $1/*
		ls -l $1 | grep ".sh" && echo -e "\n$hr\n"
		# Running..
		find $1 -type f -name '*.sh' | sort | \
		while read file; do run_script "$file"; done
	else
        echo -e "No '$TYPE' scripts to run\n$hr"	
	fi
}
