name: Build Go

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.15", "1.14", "1.13", "1.12", "1.11"]
    name: Go build (${{ matrix.go }})
    steps:
      - uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Go test
        run: go test -v  -timeout=5s -race ./...
